# -*- coding: utf-8 -*-
"""predict.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7wWk_oyhlUctuLYFbA_69kZ-kyvGr0X
"""

import argparse, json, re, sys
from pathlib import Path
import numpy as np
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from peft import PeftModel

PMAP  = {'Low':0,'Medium':1,'High':2,'Critical':3}
RPMAP = {v:k for k,v in PMAP.items()}
BASE  = "microsoft/deberta-v3-small"

REQUIRED = ['Ticket_ID','Ticket_Subject','Ticket_Description','Issue_Category',
            'Priority_Level','Ticket_Channel','Resolution_Time_Hours','Satisfaction_Score']

ESCA_EV = [
    (r'\bfraud\w*\b',               'fraud_indicator',    0.35),
    (r'\bphish\w*\b',               'security_threat',    0.35),
    (r'\bhack\w*\b',                'security_threat',    0.30),
    (r'\bstolen\b',                 'security_threat',    0.30),
    (r'\bunauthori[sz]ed\b',        'security_threat',    0.28),
    (r'\bdata\s+breach\b',          'data_risk',          0.32),
    (r'\bdata\s+loss\b',            'data_risk',          0.30),
    (r'\bcrash\w*\b',               'system_failure',     0.22),
    (r'\bnot\s+(loading|working|responding)\b', 'functional_failure', 0.20),
    (r'\blocke?d\s+out\b',          'access_blocked',     0.24),
    (r'\bpayment\s+fail\w*\b',      'payment_failure',    0.22),
    (r'\bcompromised\b',            'account_risk',       0.28),
    (r'\bimmediately\b',            'urgency',            0.14),
    (r'\burgent\b',                 'urgency',            0.14),
    (r'\bransomware\b',             'security_threat',    0.40),
    (r'\bmalware\b',                'security_threat',    0.38),
]
DEESC_EV = [
    (r'\bhow\s+do\s+i\b',     'informational', -0.14),
    (r'\bwhere\s+is\b',       'informational', -0.14),
    (r'\bfeature\s+request\b','feature_req',   -0.16),
    (r'\bheadquarters\b',     'general_query', -0.20),
    (r'\broadmap\b',          'general_query', -0.16),
]
RT_BENCH = {
    ('Fraud','Critical'):4,    ('Fraud','High'):12,    ('Fraud','Medium'):28,
    ('Technical','Critical'):5,('Technical','High'):18,('Technical','Medium'):38, ('Technical','Low'):50,
    ('Billing','Critical'):6,  ('Billing','High'):20,  ('Billing','Medium'):42,   ('Billing','Low'):52,
    ('Account','High'):22,     ('Account','Medium'):40,('Account','Low'):50,
    ('General Inquiry','Medium'):35, ('General Inquiry','Low'):45,
}
CAT_SEV = {
    'Fraud':          {'exp':'Critical','w':0.28,'note':'Fraud carries inherent security risk'},
    'Technical':      {'exp':'High',    'w':0.18,'note':'Technical failures impact availability'},
    'Account':        {'exp':'Medium',  'w':0.12,'note':'Account issues affect user access'},
    'Billing':        {'exp':'Medium',  'w':0.10,'note':'Billing issues have financial impact'},
    'General Inquiry':{'exp':'Low',     'w':-0.15,'note':'General inquiries are informational'},
}

def rt_tier(h):
    if h<=10: return 'FAST'
    if h<=45: return 'MID'
    return 'SLOW'

def make_input(row):
    rt = float(row.get('Resolution_Time_Hours', 30))
    return (f"[SUBJ] {row['Ticket_Subject']} "
            f"[BODY] {row['Ticket_Description']} "
            f"| cat:{row['Issue_Category']} "
            f"| ch:{row['Ticket_Channel']} "
            f"| rt:{rt_tier(rt)} "
            f"| pri:{row['Priority_Level']}")

def load_model(mdl_dir, device):
    best = mdl_dir/'best'
    if not best.exists():
        sys.exit(f"No model at {best}. Run train_pipeline.py first.")
    tok   = AutoTokenizer.from_pretrained(str(best))
    base  = AutoModelForSequenceClassification.from_pretrained(BASE, num_labels=2, ignore_mismatched_sizes=True)
    model = PeftModel.from_pretrained(base, str(best)).float().to(device)
    model.eval()
    tf = mdl_dir/'threshold.npy'
    thr = float(np.load(str(tf))[0]) if tf.exists() else 0.5
    return tok, model, thr

def infer_batch(texts, tok, model, device, bs=64):
    probs = []
    for i in range(0, len(texts), bs):
        enc = tok(texts[i:i+bs], truncation=True, padding='max_length',
                  max_length=256, return_tensors='pt')
        enc = {k:v.to(device) for k,v in enc.items()}
        with torch.no_grad():
            out = model(**enc)
        probs += torch.softmax(out.logits.float(), -1)[:,1].cpu().tolist()
    return np.array(probs)

def dir_score(row):
    t   = f"{row['Ticket_Subject']} {row['Ticket_Description']}".lower()
    s   = sum(w for _,_,w in ESCA_EV+DEESC_EV if re.search(_,t))
    cat = row['Issue_Category']; pri = row['Priority_Level']
    cs  = CAT_SEV.get(cat, {'exp':'Medium','w':0.05})
    if PMAP.get(cs['exp'],1) > PMAP.get(pri,1): s += abs(cs['w'])
    elif PMAP.get(cs['exp'],1) < PMAP.get(pri,1): s -= abs(cs['w'])
    sat = int(row['Satisfaction_Score'])
    if sat<=2 and pri in ('Low','Medium'): s+=0.18
    elif sat>=4 and pri in ('Critical','High'): s-=0.12
    rt  = float(row['Resolution_Time_Hours'])
    exp = RT_BENCH.get((cat,pri), 40.0)
    r   = rt/max(exp,1)
    if r<0.4: s+=0.14
    elif r>2.5: s+=0.10
    return s

def get_verdict(row, prob):
    base = PMAP.get(row['Priority_Level'],1)
    d    = dir_score(row)
    if d < 0:
        bump     = 2 if prob>=0.90 else 1
        mtype    = 'False Alarm'
        inf_ord  = max(0, base-bump)
    else:
        bump     = 2 if prob>=0.85 else 1
        mtype    = 'Hidden Crisis'
        inf_ord  = min(3, base+bump)
    return RPMAP[inf_ord], mtype

def ev_text(row, mtype):
    t  = f"{row['Ticket_Subject']} {row['Ticket_Description']}".lower()
    ev = []
    for pat, etype, w in ESCA_EV+DEESC_EV:
        m = re.search(pat, t)
        if m:
            fld = 'Ticket_Subject' if re.search(pat, row['Ticket_Subject'].lower()) else 'Ticket_Description'
            ev.append({'signal':'keyword','type':etype,'value':m.group(0),'source_field':fld,'weight':round(w,3)})
    ev = [e for e in ev if (e['weight']>0) == (mtype=='Hidden Crisis')]
    return ev

def ev_rt(row, mtype):
    rt   = float(row['Resolution_Time_Hours'])
    cat  = row['Issue_Category']; pri = row['Priority_Level']
    exp  = RT_BENCH.get((cat,pri), 40.0)
    r    = rt/max(exp,1)
    if r<0.4:
        interp = f"Resolved in {rt:.0f}h vs ~{exp:.0f}h expected — {r:.1f}x faster, {'consistent with over-triage' if mtype=='False Alarm' else 'suggests true urgency exceeded the label'}"
        w = 0.25
    elif r>2.5:
        interp = f"Resolved in {rt:.0f}h vs ~{exp:.0f}h expected — {r:.1f}x slower, suggesting under-resourcing"
        w = 0.20
    else:
        interp = f"Resolved in {rt:.0f}h — within normal range for {pri} {cat} (~{exp:.0f}h)"
        w = 0.05
    return {'signal':'resolution_time','value':f"{rt:.0f}h",'expected':f"~{exp:.0f}h",
            'rt_ratio':round(r,2),'source_field':'Resolution_Time_Hours','interpretation':interp,'weight':round(w,3)}

def ev_sat(row, mtype):
    sat = int(row['Satisfaction_Score']); pri = row['Priority_Level']
    if mtype=='Hidden Crisis' and sat<=2 and pri in ('Low','Medium'):
        interp = f"Sat {sat}/5 on {pri} ticket — low satisfaction signals severity beyond assigned level"
        w = 0.18
    elif mtype=='False Alarm' and sat>=4 and pri in ('Critical','High'):
        interp = f"Sat {sat}/5 on {pri} ticket — high satisfaction consistent with over-triage"
        w = 0.12
    else:
        interp = f"Sat {sat}/5 — insufficient signal for {mtype} independently"
        w = 0.02
    return {'signal':'satisfaction_score','value':str(sat),'source_field':'Satisfaction_Score',
            'interpretation':interp,'weight':round(w,3)}

def ev_cat(row, mtype):
    cat = row['Issue_Category']; pri = row['Priority_Level']
    cs  = CAT_SEV.get(cat, {'exp':'Medium','w':0.05,'note':'Standard category'})
    eo  = PMAP.get(cs['exp'],1); po = PMAP.get(pri,1)
    if mtype=='Hidden Crisis' and eo>po:
        interp = f"{cat} warrants {cs['exp']} priority — {pri} is below baseline. {cs['note']}."
        w = abs(cs['w'])
    elif mtype=='False Alarm' and eo<po:
        interp = f"{cat} warrants {cs['exp']} priority — {pri} exceeds baseline. {cs['note']}."
        w = -abs(cs['w'])
    else:
        interp = f"{cat} assigned {pri} — within expected range."
        w = 0.03
    return {'signal':'category_baseline','value':cat,'expected_level':cs['exp'],
            'source_field':'Issue_Category','interpretation':interp,'weight':round(w,3)}

def delta_str(assigned, inferred):
    a = PMAP.get(assigned,1); i = PMAP.get(inferred,1); d = i-a
    if d>0:  return f"+{d} (under-prioritised by {d} level{'s' if d>1 else ''})"
    if d<0:  return f"{d} (over-prioritised by {abs(d)} level{'s' if abs(d)>1 else ''})"
    return "0 (borderline — signal conflict at same ordinal)"

def build_constraint(row, inferred, mtype, ev):
    cat = row['Issue_Category']; ch = row['Ticket_Channel']; pri = row['Priority_Level']
    rt  = float(row['Resolution_Time_Hours']); sat = int(row['Satisfaction_Score'])
    kp  = [e for e in ev if e['signal']=='keyword' and e.get('weight',0)>0]
    kn  = [e for e in ev if e['signal']=='keyword' and e.get('weight',0)<0]
    s1  = (f"This {cat} ticket submitted via {ch} was assigned {pri} priority, "
           f"but the model infers {inferred} severity from its content and metadata.")
    if mtype=='Hidden Crisis' and kp:
        s2 = f"Escalation indicators ({', '.join(repr(e['value']) for e in kp[:2])}) signal urgency beyond the assigned label."
    elif mtype=='False Alarm' and kn:
        s2 = f"Low-severity indicators ({', '.join(repr(e['value']) for e in kn[:2])}) suggest the ticket does not warrant {pri}."
    else:
        s2 = "Semantic patterns and metadata jointly signal a priority mismatch."
    s3 = (f"Resolution in {rt:.0f}h with satisfaction {sat}/5 "
          + ("supports under-prioritisation — earlier escalation would have reduced customer impact."
             if mtype=='Hidden Crisis'
             else f"suggests the issue was less severe than {pri} implies — resources may have been over-allocated."))
    return f"{s1} {s2} {s3}"

def build_dossier(row, prob):
    inferred, mtype = get_verdict(row, prob)
    kev  = ev_text(row, mtype)
    rtev = ev_rt(row, mtype)
    sev  = ev_sat(row, mtype)
    cev  = ev_cat(row, mtype)
    alev = sorted(kev+[rtev,sev,cev], key=lambda x:abs(x.get('weight',0)), reverse=True)
    return {
        'ticket_id':          str(row['Ticket_ID']),
        'assigned_priority':  row['Priority_Level'],
        'inferred_severity':  inferred,
        'mismatch_type':      mtype,
        'severity_delta':     delta_str(row['Priority_Level'], inferred),
        'confidence':         round(float(prob),4),
        'feature_evidence':   alev,
        'constraint_analysis':build_constraint(row, inferred, mtype, alev),
    }

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--input',      required=True)
    p.add_argument('--output',     default='outputs')
    p.add_argument('--model-dir',  default='models/sia_model')
    p.add_argument('--threshold',  type=float, default=None)
    p.add_argument('--batch-size', type=int,   default=64)
    args = p.parse_args()

    out = Path(args.output); out.mkdir(parents=True, exist_ok=True)
    mdl = Path(args.model_dir)
    if not Path(args.input).exists(): sys.exit(f"ERROR: {args.input} not found")

    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Device: {device}")

    df = pd.read_csv(args.input)
    miss = [c for c in REQUIRED if c not in df.columns]
    if miss: sys.exit(f"Missing columns: {miss}")
    for c in ['Ticket_Subject','Ticket_Description','Issue_Category','Ticket_Channel','Priority_Level']:
        df[c] = df[c].astype(str)
    print(f"Loaded {len(df):,} tickets")

    tok, model, saved_thr = load_model(mdl, device)
    thr = args.threshold if args.threshold is not None else saved_thr
    print(f"Threshold: {thr:.2f}")

    texts             = df.apply(make_input, axis=1).tolist()
    probs             = infer_batch(texts, tok, model, device, args.batch_size)
    df['prob']        = probs
    df['predicted']   = (probs>=thr).astype(int)
    df['verdict']     = df['predicted'].map({0:'Consistent',1:'Mismatch'})

    n = df['predicted'].sum()
    print(f"Flagged: {n:,}/{len(df):,} ({n/len(df)*100:.1f}%)")

    df[['Ticket_ID','Priority_Level','Issue_Category','prob','predicted','verdict']].to_csv(
        out/'predictions.csv', index=False)
    print(f"Saved: {out/'predictions.csv'}")

    flagged  = df[df['predicted']==1]
    dossiers = [build_dossier(r, r['prob']) for _,r in flagged.iterrows()]
    with open(out/'evidence_dossiers.json','w') as f:
        json.dump(dossiers, f, indent=2)
    print(f"Saved: {len(dossiers):,} dossiers → {out/'evidence_dossiers.json'}")

    hc = sum(1 for d in dossiers if d['mismatch_type']=='Hidden Crisis')
    fa = sum(1 for d in dossiers if d['mismatch_type']=='False Alarm')
    print(f"HC={hc:,}  FA={fa:,}")
    print("✓ Done")

def main():
    p = argparse.ArgumentParser()
    
    p.add_argument('--input',       default='/data/customer_support_tickets.csv')
    p.add_argument('--output',      default='outputs')
    p.add_argument('--model-dir',   default='models/sia_model')
    p.add_argument('--threshold',   type=float, default=None)
    p.add_argument('--batch-size',  type=int,   default=64)

    # Colab mein bina error run karne ke liye args=[]
    args = p.parse_args(args=[])

    out = Path(args.output); out.mkdir(parents=True, exist_ok=True)
    mdl = Path(args.model_dir)
    if not Path(args.input).exists(): sys.exit(f"ERROR: {args.input} not found")

    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Device: {device}")

    df = pd.read_csv(args.input)
    miss = [c for c in REQUIRED if c not in df.columns]
    if miss: sys.exit(f"Missing columns: {miss}")
    for c in ['Ticket_Subject','Ticket_Description','Issue_Category','Ticket_Channel','Priority_Level']:
        df[c] = df[c].astype(str)
    print(f"Loaded {len(df):,} tickets")

    tok, model, saved_thr = load_model(mdl, device)
    thr = args.threshold if args.threshold is not None else saved_thr
    print(f"Threshold: {thr:.2f}")

    texts             = df.apply(make_input, axis=1).tolist()
    probs             = infer_batch(texts, tok, model, device, args.batch_size)
    df['prob']        = probs
    df['predicted']   = (probs>=thr).astype(int)
    df['verdict']     = df['predicted'].map({0:'Consistent',1:'Mismatch'})

    n = df['predicted'].sum()
    print(f"Flagged: {n:,}/{len(df):,} ({n/len(df)*100:.1f}%)")

    df[['Ticket_ID','Priority_Level','Issue_Category','prob','predicted','verdict']].to_csv(
        out/'predictions.csv', index=False)
    print(f"Saved: {out/'predictions.csv'}")

    flagged  = df[df['predicted']==1]
    dossiers = [build_dossier(r, r['prob']) for _,r in flagged.iterrows()]
    with open(out/'evidence_dossiers.json','w') as f:
        json.dump(dossiers, f, indent=2)
    print(f"Saved: {len(dossiers):,} dossiers → {out/'evidence_dossiers.json'}")

    hc = sum(1 for d in dossiers if d['mismatch_type']=='Hidden Crisis')
    fa = sum(1 for d in dossiers if d['mismatch_type']=='False Alarm')
    print(f"HC={hc:,}  FA={fa:,}")
    print("✓ Done")

if __name__ == '__main__':
    main()
