# -*- coding: utf-8 -*-
"""train_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7wWk_oyhlUctuLYFbA_69kZ-kyvGr0X
"""

!pip install --upgrade torchao

import argparse, json, re, sys, warnings, pickle
from pathlib import Path
import numpy as np
import pandas as pd
import torch, torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
warnings.filterwarnings('ignore')

PMAP   = {'Low':0,'Medium':1,'High':2,'Critical':3}
RPMAP  = {v:k for k,v in PMAP.items()}
BASE   = "microsoft/deberta-v3-small"
SEED   = 42

CRIT_KW = [
    r'\bphish\w*\b', r'\bfraud\w*\b', r'\bhack\w*\b', r'\bstolen\b',
    r'\bunauthori[sz]ed\b', r'\bdata\s+breach\b', r'\bransomware\b',
    r'\bmalware\b', r'\bidentity\s+theft\b', r'\bcompromised\b',
]
HIGH_KW = [
    r'\bcrash\w*\b', r'\bnot\s+(loading|working|responding|syncing)\b',
    r'\bcannot\s+(access|log)', r'\boutage\b', r'\blocke?d\s+out\b',
    r'\bpayment\s+fail\w*\b', r'\bdata\s+loss\b', r'\bbroken\b',
    r'\berror\b', r'\bdown\b', r'\bunable\s+to\b', r'\bcorrupt\w*\b',
]
LOW_KW   = [r'\bhow\s+do\s+i\b', r'\bwhere\s+is\b', r'\bheadquarters\b',
            r'\broadmap\b', r'\bfeature\s+request\b', r'\bhours\s+of\s+operation\b']
URG_KW   = [r'\bimmediately\b', r'\burgent\b', r'\basap\b', r'\bcritical\b']

CAT_W = {'Fraud':0.88,'Technical':0.52,'Account':0.38,'Billing':0.30,'General Inquiry':0.08}

def score_keyword(row):
    t = f"{row['Ticket_Subject']} {row['Ticket_Description']}".lower()
    s  = sum(0.32 for p in CRIT_KW if re.search(p, t))
    s += sum(0.20 for p in HIGH_KW if re.search(p, t))
    s -= sum(0.14 for p in LOW_KW  if re.search(p, t))
    s += sum(0.14 for p in URG_KW  if re.search(p, t))
    ts = float(np.clip(s / (abs(s) + 3.0 + 1e-9), 0, 1)) if s != 0 else 0.0
    return float(np.clip(0.60 * ts + 0.40 * CAT_W.get(row['Issue_Category'], 0.30), 0, 1))

def build_rt_medians(df):
    return (df.groupby(['Issue_Category','Priority_Level'])['Resolution_Time_Hours']
              .median().to_dict(),
            df.groupby('Priority_Level')['Resolution_Time_Hours'].median().to_dict())

def score_rt(row, grp_med, pri_med):
    actual   = float(row['Resolution_Time_Hours'])
    prio     = row['Priority_Level']
    prio_w   = PMAP[prio] / 3.0
    expected = grp_med.get((row['Issue_Category'], prio), pri_med.get(prio, 36.0))
    ratio    = actual / max(expected, 1.0)
    log_r    = float(np.log(max(ratio, 0.01)))
    if log_r > 0:
        sig = prio_w * float(np.tanh(log_r * 0.8))
    else:
        sig = (1 - prio_w) * float(np.tanh(-log_r * 0.5))
    return float(np.clip(sig, 0, 1))

SEV_TERMS = set(
    'cannot access locked stolen phishing fraud hacked unauthorized crash '
    'error fail broken outage down missing corrupted urgent data loss breach '
    'malware ransomware compromised account suspended payment charge suspicious '
    'unable sync attack security'.split()
)
ROUT_TERMS = set(
    'how where question general inquiry feature request roadmap headquarters '
    'information looking update plan curious wondering schedule'.split()
)
CAT_BASE = {'Fraud':0.82,'Technical':0.50,'Account':0.36,'Billing':0.30,'General Inquiry':0.10}

def score_lexical(row):
    words  = re.findall(r'\b\w+\b', f"{row['Ticket_Subject']} {row['Ticket_Description']}".lower())
    if not words: return 0.3
    total  = len(words)
    sev_h  = sum(1 for w in words if w in SEV_TERMS)  / total
    rout_h = sum(1 for w in words if w in ROUT_TERMS) / total
    lex    = float(np.clip(sev_h * 14.0 - rout_h * 7.0, 0, 1))
    sat    = (5 - int(row['Satisfaction_Score'])) / 4.0
    cat    = CAT_BASE.get(row['Issue_Category'], 0.28)
    return float(np.clip(0.45 * lex + 0.35 * sat + 0.20 * cat, 0, 1))

def score_semantic(df, out_dir):
    texts = (df['Ticket_Subject'].fillna('') + '. ' +
             df['Ticket_Description'].fillna('') +
             ' cat:' + df['Issue_Category'].fillna('') +
             ' ch:'  + df['Ticket_Channel'].fillna('')).tolist()
    try:
        from sentence_transformers import SentenceTransformer
        E = SentenceTransformer('all-MiniLM-L6-v2').encode(
            texts, batch_size=64, show_progress_bar=True, normalize_embeddings=True)
    except Exception:
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.decomposition import TruncatedSVD
        from sklearn.preprocessing import normalize
        tv = TfidfVectorizer(max_features=6000, ngram_range=(1,2), sublinear_tf=True)
        E  = normalize(TruncatedSVD(100, random_state=SEED).fit_transform(tv.fit_transform(texts)))

    try:
        import umap
        E2 = umap.UMAP(n_components=8, n_neighbors=15, min_dist=0.05,
                       metric='cosine', random_state=SEED, verbose=False).fit_transform(E)
    except Exception:
        from sklearn.decomposition import PCA
        E2 = PCA(n_components=min(8, E.shape[1]-1), random_state=SEED).fit_transform(E)

    try:
        import hdbscan
        labels = hdbscan.HDBSCAN(min_cluster_size=30, min_samples=8,
                                  metric='euclidean').fit_predict(E2)
    except Exception:
        from sklearn.cluster import KMeans
        labels = KMeans(n_clusters=12, random_state=SEED, n_init=10).fit_predict(E2)

    df['_cid'] = labels
    cmap = {}
    for cid in set(labels):
        if cid == -1: continue
        cmap[cid] = df[df['_cid']==cid]['priority_ord'].mean()
    if cmap:
        lo, hi = min(cmap.values()), max(cmap.values())
        sig = [float(np.clip((cmap.get(c, lo)-lo)/(hi-lo+1e-9), 0, 1))
               if c != -1 else 0.5 for c in labels]
    else:
        sig = [0.5] * len(df)

    np.save(str(out_dir/'emb_reduced.npy'), E2)
    np.save(str(out_dir/'cluster_ids.npy'), labels)
    return np.array(sig)

def run_fusion(df, out_dir, mdl_dir):
    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import cross_val_score, StratifiedKFold
    from sklearn.metrics import cohen_kappa_score
    from scipy.stats import spearmanr

    SIGS  = ['sig_kw','sig_rt','sig_lex','sig_sem']
    NAMES = {'sig_kw':'NLP Keywords','sig_rt':'RT Mismatch',
             'sig_lex':'Lexical+Sat','sig_sem':'Semantic Cluster'}

    print("\nPairwise Cohen's κ:")
    for i, s1 in enumerate(SIGS):
        for s2 in SIGS[i+1:]:
            b1 = (df[s1]>=0.5).astype(int)
            b2 = (df[s2]>=0.5).astype(int)
            k  = cohen_kappa_score(b1, b2)
            a  = (b1==b2).mean()*100
            print(f"  {NAMES[s1][:16]:16s} x {NAMES[s2][:16]:16s}  κ={k:.3f}  agree={a:.1f}%")

    ablation = {}
    print("\nAblation:")
    for s in SIGS:
        rho, _ = spearmanr(df[s], df['priority_ord'])
        acc1   = ((df[s].apply(lambda x: 3 if x>=.75 else 2 if x>=.50 else 1 if x>=.25 else 0)
                   - df['priority_ord']).abs().le(1)).mean()
        print(f"  {NAMES[s]:20s}  rho={rho:.3f}  acc@1={acc1*100:.1f}%")
        ablation[NAMES[s]] = {'spearman_rho': round(rho,4), 'acc_within1': round(acc1,4)}

    X  = df[SIGS].values
    sc = StandardScaler()
    Xs = sc.fit_transform(X)
    y  = (df['priority_ord'] >= 2).astype(int).values

    lr = LogisticRegression(C=1.0, class_weight='balanced', max_iter=500, random_state=SEED)
    cv = StratifiedKFold(5, shuffle=True, random_state=SEED)
    a  = cross_val_score(lr, Xs, y, cv=cv, scoring='accuracy')
    f  = cross_val_score(lr, Xs, y, cv=cv, scoring='f1_macro')
    print(f"\nFusion CV: acc={a.mean():.3f}±{a.std():.3f}  f1={f.mean():.3f}±{f.std():.3f}")

    lr.fit(Xs, y)
    df['sev_score'] = lr.predict_proba(Xs)[:, 1]

    wts = dict(zip(SIGS, np.abs(lr.coef_[0])))
    tot = sum(wts.values()) + 1e-9
    print("\nFusion weights:")
    for s, w in sorted(wts.items(), key=lambda x: -x[1]):
        pct = w/tot*100
        ablation[NAMES[s]]['fusion_weight_pct'] = round(pct,1)
        print(f"  {NAMES[s]:20s}: {pct:.1f}%")

    with open(out_dir/'ablation_table.json','w') as f_:
        json.dump(ablation, f_, indent=2)
    with open(mdl_dir/'fusion_model.pkl','wb') as f_:
        pickle.dump({'model':lr,'scaler':sc,'cols':SIGS}, f_)

    return df

def assign_labels(df):
    def to_sev(s):
        if s>=0.75: return 'Critical'
        if s>=0.50: return 'High'
        if s>=0.25: return 'Medium'
        return 'Low'

    df['inferred_sev'] = df['sev_score'].apply(to_sev)
    df['inferred_ord'] = df['inferred_sev'].map(PMAP)
    df['delta']        = df['inferred_ord'] - df['priority_ord']
    df['label']        = (df['delta'].abs() >= 2).astype(int)

    def mtype(r):
        if r['label'] == 0: return 'Consistent'
        return 'Hidden Crisis' if r['delta'] >= 2 else 'False Alarm'
    df['mtype'] = df.apply(mtype, axis=1)

    print(f"\nMismatch rate: {df['label'].mean()*100:.1f}%")
    print(df['mtype'].value_counts().to_string())
    return df

def stage1(csv_path, out_dir, mdl_dir):
    print("="*55 + "\nSTAGE 1 — Pseudo-label Generation\n" + "="*55)
    df = pd.read_csv(csv_path)
    df['priority_ord'] = df['Priority_Level'].map(PMAP)
    print(f"Loaded {len(df):,} tickets")

    print("Signal 1: keyword NLP...")
    df['sig_kw']  = df.apply(score_keyword, axis=1)

    print("Signal 2: RT mismatch...")
    gm, pm        = build_rt_medians(df)
    df['sig_rt']  = df.apply(lambda r: score_rt(r, gm, pm), axis=1)

    print("Signal 3: lexical + satisfaction...")
    df['sig_lex'] = df.apply(score_lexical, axis=1)

    print("Signal 4: semantic clustering...")
    df['sig_sem'] = score_semantic(df, out_dir)

    df = run_fusion(df, out_dir, mdl_dir)
    df = assign_labels(df)

    out = out_dir / 'labeled_tickets.csv'
    df.to_csv(out, index=False)
    print(f"\nSaved: {out}")
    return df


def rt_tier(h):
    if h <= 10: return 'FAST'
    if h <= 45: return 'MID'
    return 'SLOW'

def make_input(row):
    rt = float(row.get('Resolution_Time_Hours', 30))
    return (f"[SUBJ] {row['Ticket_Subject']} "
            f"[BODY] {row['Ticket_Description']} "
            f"| cat:{row['Issue_Category']} "
            f"| ch:{row['Ticket_Channel']} "
            f"| rt:{rt_tier(rt)} "
            f"| pri:{row['Priority_Level']}")

class TicketDS(Dataset):
    def __init__(self, texts, labels, tok):
        self.enc = tok(list(texts), truncation=True, padding='max_length',
                       max_length=256, return_tensors='pt')
        self.y   = torch.tensor(labels, dtype=torch.long)
    def __len__(self): return len(self.y)
    def __getitem__(self, i):
        return {k: v[i] for k, v in self.enc.items()} | {'labels': self.y[i]}

def run_eval(model, loader, device, thr=0.5):
    from sklearn.metrics import accuracy_score, f1_score
    model.eval()
    probs, ys = [], []
    with torch.no_grad():
        for b in loader:
            ids = b['input_ids'].to(device)
            msk = b['attention_mask'].to(device)
            out = model(input_ids=ids, attention_mask=msk)
            probs += torch.softmax(out.logits.float(), -1)[:,1].cpu().tolist()
            ys    += b['labels'].tolist()
    probs = np.array(probs); ys = np.array(ys)
    preds = (probs >= thr).astype(int)
    acc   = accuracy_score(ys, preds)
    f1    = f1_score(ys, preds, average='macro', zero_division=0)
    f1c   = f1_score(ys, preds, average=None,   zero_division=0)
    return acc, f1, f1c, probs, ys

def stage2(df, mdl_dir, epochs, batch_size):
    from sklearn.model_selection import train_test_split
    from sklearn.utils import resample
    from sklearn.metrics import classification_report, confusion_matrix
    from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_cosine_schedule_with_warmup
    from peft import LoraConfig, get_peft_model, TaskType, PeftModel

    print("\n" + "="*55 + "\nSTAGE 2 — DeBERTa-v3-small + LoRA\n" + "="*55)
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Device: {device}" + (f" | {torch.cuda.get_device_name(0)}" if device=='cuda' else ''))

    for c in ['Ticket_Subject','Ticket_Description','Issue_Category','Ticket_Channel','Priority_Level']:
        df[c] = df[c].astype(str)

    df['input_text'] = df.apply(make_input, axis=1)
    X = df['input_text'].values
    y = df['label'].values.astype(int)

    X_tv, X_te, y_tv, y_te = train_test_split(X, y, test_size=0.10, stratify=y, random_state=SEED)
    X_tr, X_va, y_tr, y_va = train_test_split(X_tv, y_tv, test_size=0.111, stratify=y_tv, random_state=SEED)

    Xmaj, ymaj = X_tr[y_tr==0], y_tr[y_tr==0]
    Xmin, ymin = X_tr[y_tr==1], y_tr[y_tr==1]
    n_up = len(Xmaj)//3
    Xmin_up = resample(Xmin, n_samples=n_up, replace=True, random_state=SEED)
    Xb = np.concatenate([Xmaj, Xmin_up])
    yb = np.concatenate([ymaj, np.ones(n_up, int)])
    idx = np.random.RandomState(SEED).permutation(len(Xb))
    Xb, yb = Xb[idx], yb[idx]
    print(f"Train: {len(Xb):,}  Val: {len(X_va):,}  Test: {len(X_te):,}")
    print(f"Balanced — C:{(yb==0).sum():,}  M:{(yb==1).sum():,}")

    tok     = AutoTokenizer.from_pretrained(BASE)
    tr_ds   = TicketDS(Xb,   yb,   tok)
    va_ds   = TicketDS(X_va, y_va, tok)
    te_ds   = TicketDS(X_te, y_te, tok)
    tr_ld   = DataLoader(tr_ds, batch_size=batch_size, shuffle=True)
    va_ld   = DataLoader(va_ds, batch_size=32)
    te_ld   = DataLoader(te_ds, batch_size=32)

    base_m  = AutoModelForSequenceClassification.from_pretrained(BASE, num_labels=2, ignore_mismatched_sizes=True)
    lcfg    = LoraConfig(task_type=TaskType.SEQ_CLS, r=16, lora_alpha=32, lora_dropout=0.1,
                         bias='none', target_modules=['query_proj','key_proj','value_proj','out_proj'],
                         modules_to_save=['classifier','pooler'])
    model   = get_peft_model(base_m, lcfg).float().to(device)
    tp, tt  = model.get_nb_trainable_parameters()
    print(f"Trainable: {tp:,} ({100*tp/tt:.2f}%)")

    n0 = (yb==0).sum(); n1 = (yb==1).sum(); N = len(yb)
    wts = torch.tensor([N/(2*n0), N/(2*n1)], dtype=torch.float).to(device)
    loss_fn = nn.CrossEntropyLoss(weight=wts)

    ACCUM  = 2
    LR     = 3e-5
    steps  = (len(tr_ld)//ACCUM)*epochs
    warmup = int(0.06*steps)
    opt    = AdamW(model.parameters(), lr=LR, weight_decay=0.01)
    sch    = get_cosine_schedule_with_warmup(opt, warmup, steps)

    print(f"\nEpochs={epochs}  batch={batch_size}  accum={ACCUM}  lr={LR}")
    print(f"{'Ep':>3} {'Loss':>9} {'ValAcc':>8} {'MacroF1':>9}")
    print("-"*35)

    best_f1 = 0.0; best_ep = 0
    opt.zero_grad()
    hist = {'loss':[], 'val_f1':[]}

    for ep in range(1, epochs+1):
        model.train(); tloss = 0.0
        for i, b in enumerate(tr_ld):
            ids = b['input_ids'].to(device)
            msk = b['attention_mask'].to(device)
            lbl = b['labels'].to(device)
            out = model(input_ids=ids, attention_mask=msk)
            loss = loss_fn(out.logits.float(), lbl) / ACCUM
            loss.backward(); tloss += loss.item()*ACCUM
            if (i+1)%ACCUM == 0:
                nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                opt.step(); sch.step(); opt.zero_grad()

        vacc, vf1, _, _, _ = run_eval(model, va_ld, device)
        avg = tloss/len(tr_ld)
        hist['loss'].append(avg); hist['val_f1'].append(vf1)
        print(f"{ep:>3} {avg:>9.4f} {vacc*100:>7.2f}% {vf1:>9.4f}")

        if vf1 > best_f1:
            best_f1 = vf1; best_ep = ep
            model.save_pretrained(str(mdl_dir/'best'))
            tok.save_pretrained(str(mdl_dir/'best'))

    print(f"\nBest: ep={best_ep}  val_f1={best_f1:.4f}")

    best_base = AutoModelForSequenceClassification.from_pretrained(BASE, num_labels=2, ignore_mismatched_sizes=True)
    best_mdl  = PeftModel.from_pretrained(best_base, str(mdl_dir/'best')).float().to(device)

    _, _, _, vp, vl = run_eval(best_mdl, va_ld, device)
    best_t = 0.50; best_vf = 0.0
    for t in np.linspace(0.20, 0.80, 61):
        f = __import__('sklearn.metrics', fromlist=['f1_score']).f1_score(vl, (vp>=t).astype(int), average='macro', zero_division=0)
        if f > best_vf: best_vf = f; best_t = t
    print(f"Threshold: {best_t:.2f}  val_f1: {best_vf:.4f}")

    _, _, _, tp_arr, tl = run_eval(best_mdl, te_ld, device)
    preds = (tp_arr >= best_t).astype(int)
    from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
    acc  = accuracy_score(tl, preds)
    f1   = f1_score(tl, preds, average='macro', zero_division=0)
    cm   = confusion_matrix(tl, preds)
    rcls = cm.diagonal() / cm.sum(axis=1)

    print(f"\nTEST (thr={best_t:.2f})")
    print(classification_report(tl, preds, target_names=['Consistent','Mismatch'], zero_division=0))
    print(f"Acc  : {acc*100:.2f}%  {'✓' if acc>=0.83  else '✗'}")
    print(f"F1   : {f1:.4f}    {'✓' if f1>=0.82   else '✗'}")
    print(f"Rec-C: {rcls[0]:.4f}    {'✓' if rcls[0]>=0.78 else '✗'}")
    print(f"Rec-M: {rcls[1]:.4f}    {'✓' if rcls[1]>=0.78 else '✗'}")

    model.save_pretrained(str(mdl_dir)); tok.save_pretrained(str(mdl_dir))
    np.save(str(mdl_dir/'threshold.npy'), np.array([best_t]))

    metrics = {
        'accuracy':acc,'macro_f1':f1,'recall_consistent':float(rcls[0]),
        'recall_mismatch':float(rcls[1]),'threshold':float(best_t),
        'confusion_matrix':cm.tolist(),'best_epoch':best_ep,'history':hist,
    }
    with open(mdl_dir/'metrics.json','w') as f_: json.dump(metrics,f_,indent=2)
    print(f"\nSaved: {mdl_dir}")
    return metrics

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--data',       required=True)
    p.add_argument('--output-dir', default='outputs')
    p.add_argument('--model-dir',  default='models/sia_model')
    p.add_argument('--epochs',     type=int, default=6)
    p.add_argument('--batch-size', type=int, default=16)
    p.add_argument('--skip-stage1', action='store_true')
    args = p.parse_args()

    out = Path(args.output_dir); mdl = Path(args.model_dir)
    out.mkdir(parents=True, exist_ok=True)
    mdl.mkdir(parents=True, exist_ok=True)
    (mdl/'best').mkdir(exist_ok=True)

    if args.skip_stage1:
        pth = out/'labeled_tickets.csv'
        if not pth.exists(): sys.exit(f"ERROR: {pth} not found")
        df = pd.read_csv(pth)
    else:
        if not Path(args.data).exists(): sys.exit(f"ERROR: {args.data} not found")
        df = stage1(Path(args.data), out, mdl)

    stage2(df, mdl, args.epochs, args.batch_size)
    print("\n✓ Pipeline complete")

def main():
    p = argparse.ArgumentParser()

    # 1. CHANGE: required=True hata kar default location daal di hai
    # Dhyan dein: Yahan '/content/customer_support_tickets.csv' ki jagah apne data ka sahi path daalein
    p.add_argument('--data',       default='/content/customer_support_tickets.csv')
    p.add_argument('--output-dir', default='outputs')
    p.add_argument('--model-dir',  default='models/sia_model')
    p.add_argument('--epochs',     type=int, default=6)
    p.add_argument('--batch-size', type=int, default=16)
    p.add_argument('--skip-stage1', action='store_true')

    # 2. CHANGE: Colab ke liye args=[] likhna zaroori hai
    args = p.parse_args(args=[])

    out = Path(args.output_dir); mdl = Path(args.model_dir)
    out.mkdir(parents=True, exist_ok=True)
    mdl.mkdir(parents=True, exist_ok=True)
    (mdl/'best').mkdir(exist_ok=True)

    if args.skip_stage1:
        pth = out/'labeled_tickets.csv'
        if not pth.exists(): sys.exit(f"ERROR: {pth} not found")
        df = pd.read_csv(pth)
    else:
        if not Path(args.data).exists(): sys.exit(f"ERROR: {args.data} not found. Kripya path check karein.")
        df = stage1(Path(args.data), out, mdl)

    stage2(df, mdl, args.epochs, args.batch_size)
    print("\n✓ Pipeline complete")

if __name__ == '__main__':
    main()